spring.application.name=tvtracker
spring.datasource.url=jdbc:postgresql://localhost:5432/tvtracker
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
tvdb.api.key=8592fa0d-518e-4eb2-83db-a99e5b6ecc4b